### PR TITLE
Merge dev to staging

### PR DESCRIPTION
**Pull request by jterry64**

### CODE REVIEW

**Review by tanderegg — APPROVED** [review]
This looks good, just want to note that the merge will create a new TLS certificate for staging, and the next time any Terraform runs it will use that certificate instead (for Cloudfront at least that I've seen).  The comment says that previously the certificate was generated outside of AWS and then imported into the TF state.  I'm not sure why that was done, but going forward we'd be using an AWS-generated certificate instead.  I don't see any downside of that though.

**Comment by tanderegg** [comment]
@jterry64 Also, the commit history is pretty messy here, do we want to rebase first to merge some of those commits?

**Comment by tanderegg** [comment]
@jterry64 Re: TLS Cert, I actually just got a notice that the Staging cert is about to expire (June 9th) and can't be renewed by AWS, so actually we probably want to do this ASAP anyways.  Note that we might need to update DNS records in order to validate the new cert, @dmannarino dealt with this last time, but I believe it is pretty straightforward.

**Comment by jterry64** [comment]
@tanderegg oh I forgot that certificate issue in dev. I think @dmannarino said it ended up just automatically creating a new certificate via terraform when he did it, but I think I want to wait until he gets back to confirm the process, since I also want to get these permissions to production. 

This is why these permissions really shouldn't involve terraform changes... I might have to look if there's an easy way to move them out, or separate out the commit for the permission changes instead of merging.

**Pull request closed without merging**
